routes/web.php
    Route::get('/ajax/news/filter/{last_shown_id?}',function(Illuminate\Http\Request $request, $last_shown_id = 0){
        $last_shown_id = intval($last_shown_id);
        if ($last_shown_id < 1) {
            $last_shown_id = NULL;
        }

        $parties = $request->has('party') ? $request->get('party') : null;
        $regions = $request->has('region') ? $request->get('region') : null;
        $activities = $request->has('field') ? $request->get('field') : null;
        $organizations = $request->has('organization') ? $request->get('organization') : null;
        $confirmed_only = $request->has('confirmed_only');

        $news = \App\News::published();
        if (!empty($parties)) {
            $news = $news->whereHas('parties', function($q) use ($parties) {
                $q->whereIn('id', $parties);
            });
        }
        if (!empty($organizations)) {
            $news = $news->whereHas('organizations', function($q) use ($organizations) {
                $q->whereIn('id', $organizations);
            });
        }
        if (!empty($activities)) {
            $news = $news->whereHas('activity_fields', function($q) use ($activities) {
                $q->whereIn('id', $activities);
            });
        }
        if ($confirmed_only) {
            $news = $news->where('fact_checking_level', '=', 'high');
        }
        if(!empty($regions) && (!in_array('0', $regions))) {
            $news = $news->whereHas('regions', function($q) use ($regions) {
                $q->whereIn('id', $regions);
            });
        }

        if (!empty($last_shown_id)) {
            $news = $news->where('id', '<', $last_shown_id);
        }

        $news = $news->take(12)->get();
        return [
            'parties' => $parties,
            'regions' => $regions,
            'activities' => $activities,
            'organizations' => $organizations,
            'confirmed_only' => $confirmed_only,
            'last_shown_id' => $last_shown_id,
            'content' => view('frontend.partials.news_block', compact('news'))->render(),
            'count' => $news->count()
        ];
    })->name('filtered_news');
});



Route::get('/news/search', function (Illuminate\Http\Request $request){
    $search = $request->has('search') ? $request->get('search') : '';
    if (empty($search)) {
        return redirect('/');
    }
    $page = $request->has('page') ? intval($request->get('page')) : 1;
    if ($page < 1) $page = 1;
    $news = \App\News::published()->
        where('title', 'like', '%'.$search.'%')->
        orWhere('preview', 'like', '%'.$search.'%')->
        orWhere('body', 'like', '%'.$search.'%')->
        orWhereHas('politicians', function($q) use ($search) {
            $q->where('first_name', 'like', "%{$search}%");
        })->
        orWhereHas('parties', function($q) use ($search) {
            $q->where('name', 'like', "%{$search}%");
        })->
        orWhereHas('organizations', function($q) use ($search) {
            $q->where('name', 'like', "%{$search}%");
        })->
        forPage($page, 12);
//    return $news->toSql();
//    return $news->get();
    $news = $news->get();
    return view('frontend.news_search_result', compact('news'));
})->name('news_search');

Route::get('/news/by_tag/{tag_name}/{page?}', function ($tag_name, $page = 0){
    $page = intval($page);
    if ($page < 1) $page = 1;
    $tag = \App\Tag::where('name', '=', $tag_name)->first();
    if (!empty($tag)) {
        $news = $tag->news()->published()->
        forPage($page, 12)->get();
    } else {
        $news = [];
    }
    return view('frontend.news_search_result', compact('news'));
})->name('news_by_tag');



Route::get('/take_an_action', function () {
    return view('frontend.action');
})->name('take_an_action_page');

Route::get('/about_us', function () {
    return view('frontend.about_us');
})->name('about_us_page');

Route::get('/make_suggestion', function () {
    $suggestion = new \App\Suggestion();
    return view('frontend.suggestions.form', compact('suggestion'));
})->name('make_suggestion');
Route::resource('/frontend/suggestion', 'frontend\SuggestionsController', ['only' => 'store']);

Route::get('/opinions', function(){
    $opinions = \App\News::opinions()->get();
    return view('frontend.opinions', compact('opinions'));
})->name('opinions');

Route::post('/my_account/opinion', 'frontend\OpinionController@store')->name('post_opinion');

Route::get('/forum', function () {
    return redirect("http://forum.smartnews.in.ua/");
})->name('forum_main');

Route::get('/news_feed', 'backend\NewsController@getRSSFeed')->name('news_feed');

Route::get('/news/{slug}', function($slug){
    $news = App\News::where('slug', '=', $slug)->first();
    $comments = App\Comment::where('news_id', $news->id)->orderBy('updated_at', 'desc')->paginate(5);
    return view('frontend.single_news', compact('news', 'comments'));
})->name('news');

Route::get('news/load-more-comments/{news_id}/{page_id}', 'frontend\CommentController@ajaxLoadComments');

Route::get('/single_news/{id}', function ($id) {
    $news = App\News::findOrFail($id);
    return view('frontend.single_news', compact('news'));
})->name('single_news');
Route::get('/politician/{id}', function ($id) {
    $politician = App\Politician::findOrFail($id);
    $politicianNews = \App\News::where('title', 'LIKE', '%' . $politician->last_name . '%')->orderBy('created_at', 'desc')->get();
    return view('frontend.politician', compact('politician', 'politicianNews'));
})->name('politician');
Route::get('/party/{id}', function ($id) {
    $party = App\Party::findOrFail($id);
    return view('frontend.party', compact('party'));
})->name('party');
Route::get('/organization/{id}', function ($id) {
    $organization = App\Organization::findOrFail($id);
    $organizationNews = \App\News::where('title', 'LIKE', '%' . $organization->name . '%')->orderBy('created_at', 'desc')->get();
    return view('frontend.organization', compact('organization', 'organizationNews'));
})->name('organization');

// Reiting
Route::get('reiting', ['as' => 'index.reiting', 'uses' => 'frontend\ReitingController@index']);


Route::get('/expert/{id}', function($id){

})->name('expert_profile');

Route::get('/news/like/{news_id}', 'frontend\LikesController@like')->name('like_news');
Route::get('/news/dislike/{news_id}', 'frontend\LikesController@dislike')->name('dislike_news');

Route::group(['middleware' => ['auth']], function() {
    Route::get('/news/likes/{id}', function($id){
        $likes = \App\News::find($id)->user_like_reaction;
        return $likes;
    });
    Route::get('/my_account', function(){
        $user = auth()->user();
        $user_id = $user->id;
        $bookmarks = \App\Bookmark::get_latest();
        $my_opinions = \App\News::myOpinions()->take(6)->get();
        $tags = App\Tag::whereHas(
            'news',
            function($q1) use ($user_id){
                $q1->whereHas(
                    'likes',
                    function($q) use ($user_id) {
                        $q->where('user_id', '=', $user_id);
                    });
            })->pluck('name','id');
        return view('frontend.user', compact('user', 'tags','bookmarks','my_opinions'));
    })->name('my_account');
    Route::get('/ajax/my_account/party_stats', function(){
        $parties = App\Party::withCount(
            [
                'news' => function($q){
                    $q->whereHas(
                        'likes',
                        function($q){
                            $q->whereHas('user', function($q){
                                $q->where('id', '=', auth()->user()->id);
                            });
                        }
                    );
                }
            ]
        )->get();
        return ['keys' => $parties->pluck('name'), 'values' => $parties->pluck('news_count')];
    });
    Route::get('/ajax/my_account/bookmark/{news_id}', function($news_id){
        $result = [
            'status' => 'error'
        ];
        $user_id = auth()->user()->id;
        $bookmark = \App\Bookmark::where('user_id', '=', $user_id)->where('news_id', '=', $news_id);
        if ($bookmark->exists()){
            $deleted = $bookmark->delete();
            if ($deleted) {
                $result = [
                    'status' => 'removed'
                ];
            }
        } else {
            if (\App\News::where('id', '=', $news_id)->exists()){
                $bookmark = new \App\Bookmark;
                $bookmark->user_id = $user_id;
                $bookmark->news_id = $news_id;
                if ($bookmark->save()){
                    $result = [
                        'status' => 'created',
                    ];
                }
            }
        }
        return $result;
    });

    Route::get('comment/{id}', ['as' => 'front.comment', 'uses' => 'frontend\CommentController@store']);
});

Route::group(['middleware' => ['auth','backend_user']], function(){
    Route::get('/backend', function () {
        return view('backend.layout');
    });
    Route::resource('/backend/news_source', 'backend\NewsSourceController');
    Route::resource('/backend/news', 'backend\NewsController');
    Route::resource('/backend/tags', 'backend\TagsController');
    Route::resource('/backend/politician', 'backend\PoliticianController');
    Route::resource('/backend/party', 'backend\PartyController');
    Route::resource('/backend/organization', 'backend\OrganizationController');
    Route::resource('/backend/promise', 'backend\PromiseController');
    Route::resource('/backend/users', 'backend\UserController');
    Route::resource('/backend/news_changes_log', 'backend\ActionsLogController', ['only' => 'index']);
    Route::resource('/backend/activity_fields', 'backend\ActivityFieldController');
    Route::resource('/backend/suggestions', 'backend\SuggestionsController');

app/Http/Controllers/backend/ActionsLogController.php
<?php

namespace App\Http\Controllers\backend;

use App\ActionsLog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\News;
use App\User;
use App\Traits\SortableTrait;
use App\Traits\SearchableTrait;

class ActionsLogController extends Controller
{

    use SortableTrait, SearchableTrait;

    protected $pagination_params = [];

    protected $sortable_fields = [
        'news.id',
        'news.title',
        'users.name',
        'old_status',
        'new_status',
        'actions_log.created_at',
    ];

    protected $searchable_fields = [
        'news.id' => '=',
        'news.title' => 'like',
        'users.name' => 'like',
        'old_status' => 'like',
        'new_status' => 'like',
        'actions_log.created_at' => 'like',
    ];

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = new ActionsLog();
        $query = $query->join('users', 'user_id', '=', 'users.id');
        $query = $query->join('news', 'news_id', '=', 'news.id');
        $query = $this->build_search_query($query, $request);
        $query = $this->build_sort_query($query, $request);
        $log_entries = $query->paginate(50);
        $search_fields = $this->search_fields;
        $pagination_params = $this->pagination_params;
        return view('backend.news_actions_log.index', compact('log_entries', 'pagination_params', 'search_fields'));
    }

}

app/Http/Controllers/backend/ActivityFieldController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use App\ActivityField;

class ActivityFieldController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.activity_fields.index',['activity_fields' => ActivityField::paginate(20)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $activity_field = new ActivityField();
        return view('backend.activity_fields.edit', compact('activity_field'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $af = new ActivityField();
        $this->validate($request, [
            'name' => 'required|unique:activity_fields|max:255'
        ]);
        $data = $request->all();
        $af->fill($data);
        $af->setIconImage($request);
        $af->save();

        return redirect(route('activity_fields.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $activity_field = ActivityField::findOrFail($id);
        return view('backend.activity_fields.edit', compact('activity_field'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $af = ActivityField::findOrFail($id);
        $this->validate($request, [
            'name' => ['required', Rule::unique('activity_fields')->ignore($af->id)]
        ]);
        $data = $request->all();
        $af->fill($data);
        $af->setIconImage($request);
        $af->save();

        return redirect(route('activity_fields.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $af = ActivityField::findOrFail($id);
        $af->news()->detach();
        $af->promises()->detach();
        $af->delete();
        return redirect(route('activity_fields.index'))->with(['notification' => 'Сфера удалена']);
    }
}

app/Http/Controllers/backend/CommentController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\SortableTrait;
use App\Traits\SearchableTrait;
use App\Comment;

class CommentController extends Controller
{
    use SortableTrait, SearchableTrait;

    protected $pagination_params = [];

    protected $sortable_fields = [
        'id',
        'news_id',
        'text',
        'status',
        'created_at',
        'updated_at'
    ];

    protected $searchable_fields = [
        'id' => '=',
        'news_id' => '=',
        'user_id' => '=',
        'status' => '=',
    ];

    public function index(Request $request)
    {
        $query = new Comment();

        $query = $this->build_search_query($query, $request);
        $query = $this->build_sort_query($query, $request);

        $comments = $query->with(['news', 'user'])->orderBy('created_at', 'desc')->paginate(10);

        $search_fields = $this->search_fields;
        $pagination_params = $this->pagination_params;

        return view('backend.comments.index', compact('comments', 'pagination_params', 'search_fields'));
    }

    public function edit($id)
    {
        $comment = Comment::find($id);

        return view('backend.comments.edit', compact('comment'));
    }

    public function update(Request $request, $id)
    {
        $comment = Comment::find($id);
        $comment->text = $request->text;
        if ($request->status == 'on'){
            $comment->status = 1;
        } else {
            $comment->status = 0;
        }
        $comment->update();

        return redirect()->back();
    }

    public function destroy($id)
    {
        Comment::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/backend/news_sources/edit.blade.php
@extends('backend.layout')

@section('title', 'Источники новостей')

@section('content')
    <div class="col-md-12">
        {{
            Form::model(
                $news_source,
                [
                    'route' => $news_source->exists ? ['news_source.update',$news_source->id] : 'news_source.store',
                    'method' => $news_source->exists ? 'PATCH' : 'POST',
                    'class' => 'form-horizontal',
                    'files' => true
                ]
            )

        }}

        <div class="form-group">
            <div class="col-md-2">
                {{ Form::label('name', 'Название источника', ['class' => 'control-label']) }}
            </div>
            <div class="col-md-10">
                {{ Form::text('name', null, ['class' => 'form-control']) }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">
                {{ Form::label($news_source->logo_form_name, 'Логотип', ['class' => 'control-label']) }}
            </div>
            <div class="col-md-10">
                @if($news_source->logo_url)
                    <img src="{{$news_source->logo_url}}" alt="">
                @endif
                {{ Form::file($news_source->logo_form_name) }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">
                {{ Form::label('site_url', 'Web адрес источника') }}
            </div>
            <div class="col-md-10">
                {{ Form::text('site_url', null, ['class' => 'form-control']) }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">
                {{ Form::label('use_fake_rating', 'Использовать фейковый рейтинг') }}
            </div>
            <div class="col-md-10">
                {{ Form::checkbox('use_fake_rating', 1, null, ['class' => 'checkbox']) }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2">
                {{ Form::label('fake_rating', 'Фейковый рейтинг') }}
            </div>
            <div class="col-md-10">
                {{ Form::number('fake_rating', 0, ['class' => 'form-control', 'step' => '0.1', 'min' => 0, 'max' => 100]) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::submit('Сохранить') }}
        </div>


        {{ Form::close() }}
    </div>
@endsection

resources/views/backend/news_sources/index.blade.php
@extends('backend.layout')

@section('title', 'Источники новостей')

@section('content')
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <a href="{!! route('news_source.create') !!}" class="btn btn-default">Создать</a>
            </div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <td>id <a href="{!! route('news_source.index', array_merge($pagination_params,['sort_by'=> 'id'])) !!}"><span class="glyphicon glyphicon-sort"></span></a></td>
                <td>Название <a href="{!! route('news_source.index', array_merge($pagination_params,['sort_by'=> 'name'])) !!}"><span class="glyphicon glyphicon-sort"></span></a></td>
                <td>Ссылка</td>
                <td>Подтвержденных фактов</td>
                <td>Всего новостей</td>
                <td>Рейтинг  <a href="{!! route('news_source.index', array_merge($pagination_params,['sort_by'=> 'rating'])) !!}"><span class="glyphicon glyphicon-sort"></span></a></td>
                <td>Лайки</td>
                <td colspan="2"></td>
            </tr>
            <tr>
                {!! Form::open(['method' => 'GET']) !!}
                <td>
                    {!! Form::input('text', 'search_fields[id]', $search_fields['id'], ['class' => 'form-control col-xs-1']) !!}
                </td>
                <td>
                    {!! Form::input('text', 'search_fields[name]', $search_fields['name'], ['class' => 'form-control']) !!}
                </td>
                <td>
                    {!! Form::input('text', 'search_fields[site_url]', $search_fields['site_url'], ['class' => 'form-control']) !!}
                </td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>

                <td>
                    {!! Form::submit('Найти', ['class' => 'form-control btn btn-primary btn-sm']) !!}
                </td>
                {!! Form::close() !!}
                <td>
                    {!! Form::open(['method' => 'GET']) !!}
                    {!! Form::submit('Сбросить', ['class' => 'form-control btn btn-warning btn-sm']) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
            </thead>
            <tbody>
            @foreach ($news_sources as $item)
                <tr>
                    <td>{!! $item['id'] !!}</td>
                    <td>{!! $item['name'] !!}</td>
                    <td><a href="http://{!! $item['site_url'] !!}">{!! $item['site_url'] !!}</a></td>
                    <td>{!! Faker\Factory::create()->randomNumber(2) !!}</td>
                    <td>{!! $item->news->count() !!}</td>
                    <td>{!! $item['rating'] !!}</td>
                    <td>
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                        {{$item->news()->withCount('likes')->get()->sum('likes_count')}}
                        /
                        <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                        {{$item->news()->withCount('dislikes')->get()->sum('dislikes_count')}}
                    </td>
                    <td>
                        {!! Form::model($item, ['route' => ['news_source.edit', $item['id']], 'method' => 'get']) !!}
                        {!! Form::button('<span class="glyphicon glyphicon-edit"></span> Изменить', ['class' => 'btn btn-warning btn-sm', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                    <td>
                        {!! Form::model($item, ['route' => ['news_source.destroy', $item['id']], 'method' => 'DELETE']) !!}
                        {!! Form::button('<span class="glyphicon glyphicon-remove"></span> Удалить', ['class' => 'btn btn-danger btn-sm', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>


    <div class="pagination">
        {!! $news_sources->appends($pagination_params)->links() !!}
    </div>
@endsection