routes/web.php
    Route::get('/ajax/news/filter/{last_shown_id?}',function(Illuminate\Http\Request $request, $last_shown_id = 0){
        $last_shown_id = intval($last_shown_id);
        if ($last_shown_id < 1) {
            $last_shown_id = NULL;
        }

        $parties = $request->has('party') ? $request->get('party') : null;
        $regions = $request->has('region') ? $request->get('region') : null;
        $activities = $request->has('field') ? $request->get('field') : null;
        $organizations = $request->has('organization') ? $request->get('organization') : null;
        $confirmed_only = $request->has('confirmed_only');

        $news = \App\News::published();
        if (!empty($parties)) {
            $news = $news->whereHas('parties', function($q) use ($parties) {
                $q->whereIn('id', $parties);
            });
        }
        if (!empty($organizations)) {
            $news = $news->whereHas('organizations', function($q) use ($organizations) {
                $q->whereIn('id', $organizations);
            });
        }
        if (!empty($activities)) {
            $news = $news->whereHas('activity_fields', function($q) use ($activities) {
                $q->whereIn('id', $activities);
            });
        }
        if ($confirmed_only) {
            $news = $news->where('fact_checking_level', '=', 'high');
        }
        if(!empty($regions) && (!in_array('0', $regions))) {
            $news = $news->whereHas('regions', function($q) use ($regions) {
                $q->whereIn('id', $regions);
            });
        }

        if (!empty($last_shown_id)) {
            $news = $news->where('id', '<', $last_shown_id);
        }

        $news = $news->take(12)->get();
        return [
            'parties' => $parties,
            'regions' => $regions,
            'activities' => $activities,
            'organizations' => $organizations,
            'confirmed_only' => $confirmed_only,
            'last_shown_id' => $last_shown_id,
            'content' => view('frontend.partials.news_block', compact('news'))->render(),
            'count' => $news->count()
        ];
    })->name('filtered_news');
});



Route::get('/news/search', function (Illuminate\Http\Request $request){
    $search = $request->has('search') ? $request->get('search') : '';
    if (empty($search)) {
        return redirect('/');
    }
    $page = $request->has('page') ? intval($request->get('page')) : 1;
    if ($page < 1) $page = 1;
    $news = \App\News::published()->
        where('title', 'like', '%'.$search.'%')->
        orWhere('preview', 'like', '%'.$search.'%')->
        orWhere('body', 'like', '%'.$search.'%')->
        orWhereHas('politicians', function($q) use ($search) {
            $q->where('first_name', 'like', "%{$search}%");
        })->
        orWhereHas('parties', function($q) use ($search) {
            $q->where('name', 'like', "%{$search}%");
        })->
        orWhereHas('organizations', function($q) use ($search) {
            $q->where('name', 'like', "%{$search}%");
        })->
        forPage($page, 12);
//    return $news->toSql();
//    return $news->get();
    $news = $news->get();
    return view('frontend.news_search_result', compact('news'));
})->name('news_search');

Route::get('/news/by_tag/{tag_name}/{page?}', function ($tag_name, $page = 0){
    $page = intval($page);
    if ($page < 1) $page = 1;
    $tag = \App\Tag::where('name', '=', $tag_name)->first();
    if (!empty($tag)) {
        $news = $tag->news()->published()->
        forPage($page, 12)->get();
    } else {
        $news = [];
    }
    return view('frontend.news_search_result', compact('news'));
})->name('news_by_tag');



Route::get('/take_an_action', function () {
    return view('frontend.action');
})->name('take_an_action_page');

Route::get('/about_us', function () {
    return view('frontend.about_us');
})->name('about_us_page');

Route::get('/make_suggestion', function () {
    $suggestion = new \App\Suggestion();
    return view('frontend.suggestions.form', compact('suggestion'));
})->name('make_suggestion');
Route::resource('/frontend/suggestion', 'frontend\SuggestionsController', ['only' => 'store']);

Route::get('/opinions', function(){
    $opinions = \App\News::opinions()->get();
    return view('frontend.opinions', compact('opinions'));
})->name('opinions');

Route::post('/my_account/opinion', 'frontend\OpinionController@store')->name('post_opinion');

Route::get('/forum', function () {
    return redirect("http://forum.smartnews.in.ua/");
})->name('forum_main');

Route::get('/news_feed', 'backend\NewsController@getRSSFeed')->name('news_feed');

Route::get('/news/{slug}', function($slug){
    $news = App\News::where('slug', '=', $slug)->first();
    $comments = App\Comment::where('news_id', $news->id)->orderBy('updated_at', 'desc')->paginate(5);
    return view('frontend.single_news', compact('news', 'comments'));
})->name('news');

Route::get('news/load-more-comments/{news_id}/{page_id}', 'frontend\CommentController@ajaxLoadComments');

Route::get('/single_news/{id}', function ($id) {
    $news = App\News::findOrFail($id);
    return view('frontend.single_news', compact('news'));
})->name('single_news');
Route::get('/politician/{id}', function ($id) {
    $politician = App\Politician::findOrFail($id);
    $politicianNews = \App\News::where('title', 'LIKE', '%' . $politician->last_name . '%')->orderBy('created_at', 'desc')->get();
    return view('frontend.politician', compact('politician', 'politicianNews'));
})->name('politician');
Route::get('/party/{id}', function ($id) {
    $party = App\Party::findOrFail($id);
    return view('frontend.party', compact('party'));
})->name('party');
Route::get('/organization/{id}', function ($id) {
    $organization = App\Organization::findOrFail($id);
    $organizationNews = \App\News::where('title', 'LIKE', '%' . $organization->name . '%')->orderBy('created_at', 'desc')->get();
    return view('frontend.organization', compact('organization', 'organizationNews'));
})->name('organization');

// Reiting
Route::get('reiting', ['as' => 'index.reiting', 'uses' => 'frontend\ReitingController@index']);


Route::get('/expert/{id}', function($id){

})->name('expert_profile');

Route::get('/news/like/{news_id}', 'frontend\LikesController@like')->name('like_news');
Route::get('/news/dislike/{news_id}', 'frontend\LikesController@dislike')->name('dislike_news');

Route::group(['middleware' => ['auth']], function() {
    Route::get('/news/likes/{id}', function($id){
        $likes = \App\News::find($id)->user_like_reaction;
        return $likes;
    });
    Route::get('/my_account', function(){
        $user = auth()->user();
        $user_id = $user->id;
        $bookmarks = \App\Bookmark::get_latest();
        $my_opinions = \App\News::myOpinions()->take(6)->get();
        $tags = App\Tag::whereHas(
            'news',
            function($q1) use ($user_id){
                $q1->whereHas(
                    'likes',
                    function($q) use ($user_id) {
                        $q->where('user_id', '=', $user_id);
                    });
            })->pluck('name','id');
        return view('frontend.user', compact('user', 'tags','bookmarks','my_opinions'));
    })->name('my_account');
    Route::get('/ajax/my_account/party_stats', function(){
        $parties = App\Party::withCount(
            [
                'news' => function($q){
                    $q->whereHas(
                        'likes',
                        function($q){
                            $q->whereHas('user', function($q){
                                $q->where('id', '=', auth()->user()->id);
                            });
                        }
                    );
                }
            ]
        )->get();
        return ['keys' => $parties->pluck('name'), 'values' => $parties->pluck('news_count')];
    });
    Route::get('/ajax/my_account/bookmark/{news_id}', function($news_id){
        $result = [
            'status' => 'error'
        ];
        $user_id = auth()->user()->id;
        $bookmark = \App\Bookmark::where('user_id', '=', $user_id)->where('news_id', '=', $news_id);
        if ($bookmark->exists()){
            $deleted = $bookmark->delete();
            if ($deleted) {
                $result = [
                    'status' => 'removed'
                ];
            }
        } else {
            if (\App\News::where('id', '=', $news_id)->exists()){
                $bookmark = new \App\Bookmark;
                $bookmark->user_id = $user_id;
                $bookmark->news_id = $news_id;
                if ($bookmark->save()){
                    $result = [
                        'status' => 'created',
                    ];
                }
            }
        }
        return $result;
    });

    Route::get('comment/{id}', ['as' => 'front.comment', 'uses' => 'frontend\CommentController@store']);
});

Route::group(['middleware' => ['auth','backend_user']], function(){
    Route::get('/backend', function () {
        return view('backend.layout');
    });
    Route::resource('/backend/news_source', 'backend\NewsSourceController');
    Route::resource('/backend/news', 'backend\NewsController');
    Route::resource('/backend/tags', 'backend\TagsController');
    Route::resource('/backend/politician', 'backend\PoliticianController');
    Route::resource('/backend/party', 'backend\PartyController');
    Route::resource('/backend/organization', 'backend\OrganizationController');
    Route::resource('/backend/promise', 'backend\PromiseController');
    Route::resource('/backend/users', 'backend\UserController');
    Route::resource('/backend/news_changes_log', 'backend\ActionsLogController', ['only' => 'index']);
    Route::resource('/backend/activity_fields', 'backend\ActivityFieldController');
    Route::resource('/backend/suggestions', 'backend\SuggestionsController');

app/Promise.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Promise extends Model
{
    protected $fillable = [
        'description',
        'quote',
        'proof_url',
        'confirmed',
        'failed',
        'comments'
    ];

    public function politicians()
    {
        return $this->belongsToMany('App\Politician');
    }

    public function parties()
    {
        return $this->belongsToMany('App\Party');
    }

    public function organizations()
    {
        return $this->belongsToMany('App\Organization');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function news()
    {
        return $this->belongsToMany('App\News');
    }

    public function activity_fields()
    {
        return $this->belongsToMany('App\ActivityField');
    }

    public function getTagIdsAttribute()
    {
        return $this->tags()->pluck('id')->toArray();
    }

    public static function getConfirmed()
    {
        return self::where('confirmed', '=', 1)->get();
    }

    public static function getFailed()
    {
        return self::where('failed', '=', 1)->get();
    }

    public static function getUnConfirmed()
    {
        return self::where('confirmed', '=', 0)->where('failed', '=', 0)->get();
    }
}

app/Http/Controllers/backend/ActionsLogController.php
<?php

namespace App\Http\Controllers\backend;

use App\ActionsLog;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\News;
use App\User;
use App\Traits\SortableTrait;
use App\Traits\SearchableTrait;

class ActionsLogController extends Controller
{

    use SortableTrait, SearchableTrait;

    protected $pagination_params = [];

    protected $sortable_fields = [
        'news.id',
        'news.title',
        'users.name',
        'old_status',
        'new_status',
        'actions_log.created_at',
    ];

    protected $searchable_fields = [
        'news.id' => '=',
        'news.title' => 'like',
        'users.name' => 'like',
        'old_status' => 'like',
        'new_status' => 'like',
        'actions_log.created_at' => 'like',
    ];

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query = new ActionsLog();
        $query = $query->join('users', 'user_id', '=', 'users.id');
        $query = $query->join('news', 'news_id', '=', 'news.id');
        $query = $this->build_search_query($query, $request);
        $query = $this->build_sort_query($query, $request);
        $log_entries = $query->paginate(50);
        $search_fields = $this->search_fields;
        $pagination_params = $this->pagination_params;
        return view('backend.news_actions_log.index', compact('log_entries', 'pagination_params', 'search_fields'));
    }

}

app/Http/Controllers/backend/ActivityFieldController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\Http\Controllers\Controller;
use App\ActivityField;

class ActivityFieldController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.activity_fields.index',['activity_fields' => ActivityField::paginate(20)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $activity_field = new ActivityField();
        return view('backend.activity_fields.edit', compact('activity_field'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $af = new ActivityField();
        $this->validate($request, [
            'name' => 'required|unique:activity_fields|max:255'
        ]);
        $data = $request->all();
        $af->fill($data);
        $af->setIconImage($request);
        $af->save();

        return redirect(route('activity_fields.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $activity_field = ActivityField::findOrFail($id);
        return view('backend.activity_fields.edit', compact('activity_field'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $af = ActivityField::findOrFail($id);
        $this->validate($request, [
            'name' => ['required', Rule::unique('activity_fields')->ignore($af->id)]
        ]);
        $data = $request->all();
        $af->fill($data);
        $af->setIconImage($request);
        $af->save();

        return redirect(route('activity_fields.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $af = ActivityField::findOrFail($id);
        $af->news()->detach();
        $af->promises()->detach();
        $af->delete();
        return redirect(route('activity_fields.index'))->with(['notification' => 'Сфера удалена']);
    }
}

app/Http/Controllers/backend/CommentController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\SortableTrait;
use App\Traits\SearchableTrait;
use App\Comment;

class CommentController extends Controller
{
    use SortableTrait, SearchableTrait;

    protected $pagination_params = [];

    protected $sortable_fields = [
        'id',
        'news_id',
        'text',
        'status',
        'created_at',
        'updated_at'
    ];

    protected $searchable_fields = [
        'id' => '=',
        'news_id' => '=',
        'user_id' => '=',
        'status' => '=',
    ];

    public function index(Request $request)
    {
        $query = new Comment();

        $query = $this->build_search_query($query, $request);
        $query = $this->build_sort_query($query, $request);

        $comments = $query->with(['news', 'user'])->orderBy('created_at', 'desc')->paginate(10);

        $search_fields = $this->search_fields;
        $pagination_params = $this->pagination_params;

        return view('backend.comments.index', compact('comments', 'pagination_params', 'search_fields'));
    }

    public function edit($id)
    {
        $comment = Comment::find($id);

        return view('backend.comments.edit', compact('comment'));
    }

    public function update(Request $request, $id)
    {
        $comment = Comment::find($id);
        $comment->text = $request->text;
        if ($request->status == 'on'){
            $comment->status = 1;
        } else {
            $comment->status = 0;
        }
        $comment->update();

        return redirect()->back();
    }

    public function destroy($id)
    {
        Comment::find($id)->delete();

        return redirect()->back();
    }
}

resources/views/backend/promises/edit.blade.php
@extends('backend.layout')

@section('title', 'Обещания')

@section('content')
    <div class="col-md-12">
        {{
            Form::model(
                $promise,
                [
                    'route' => $promise->exists ? ['promise.update',$promise->id] : 'promise.store',
                    'method' => $promise->exists ? 'PATCH' : 'POST',
                    'class' => 'form-horizontal',
                    'id' => 'promise_form'
                ]
            )

        }}

        @include('backend.promises.edit_form')

        {{ Form::close() }}

        <script>
            $(document).ready(function () {
                var $create_tag_dlg = $('#create_tag_dlg');

                $('#tag_select').on('chosen:no_results', function () {
                    $('#tag_select_chosen .no-results').html(
                        $('#tag_select_chosen .no-results').html() +
                        ' <span class="btn btn-success btn-xs" id="create_tag"><span class="glyphicon glyphicon-plus-sign"></span> Создать</span>'
                    );
                });
                $('#tag_select_chosen').delegate('#create_tag', 'click', function () {
                    $create_tag_dlg.dialog();
                });
                $('body').on('tag_created', function(event, data){
                    var $new_tag = $('<option value="'+data.id+'">'+data.name+'</option>').prop('selected', true);
                    $('#tag_select').append($new_tag).trigger('chosen:updated');
                    $create_tag_dlg.dialog('close');
                });
                $('body').on('tag_creation_error', function(event, data){
                    $create_tag_dlg.dialog('close');
                    alert('Не могу создать тег');
                });

            })
        </script>
    </div>
@endsection

resources/views/backend/promises/edit_ajax.blade.php
<div class="col-md-12">
    {{
        Form::open(
            [
                'class' => 'form-horizontal',
                'id' => 'promise_form_ajax'
            ]
        )

    }}

    @include('backend.promises.edit_form')

    {{ Form::close() }}

</div>

resources/views/backend/promises/edit_form.blade.php
<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('description', 'Общая формулировка') }}
    </div>
    <div class="col-md-10">
        {{ Form::text('description', null, ['class' => 'form-control', 'id' => 'description_input']) }}
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('quote', 'Конкретная цитата') }}
    </div>
    <div class="col-md-10">
        {{ Form::text('quote', null, ['class' => 'form-control', 'id' => 'quote_input']) }}
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('proof_url', 'Пруфлинка') }}
    </div>
    <div class="col-md-10">
        {{ Form::text('proof_url', null, ['class' => 'form-control', 'id' => 'proof_url']) }}
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('tags', 'Теги') }}
    </div>
    <div class="col-md-10">
        {{ Form::select('tags', App\Tag::getSelectValues(), $promise->tag_ids, ['multiple', 'name' => 'tags[]', 'class' => 'form-control chosen', 'id' => 'tag_select']) }}
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('activity_fields', 'Сферы', ['class' => 'control-label']) }}
    </div>
    <div class="col-md-10">
        {{ Form::select('activity_fields', App\ActivityField::getSelectOptions(), $promise->activity_fields->pluck('id')->toArray(), ['multiple', 'name' => 'activity_fields[]', 'class' => 'form-control chosen']) }}
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('promise_confirmed', 'Подтверждено') }}
    </div>
    <div class="col-md-10">
        {{ Form::checkbox('promise_confirmed', 1, $promise->confirmed, ['class' => 'checkbox']) }}
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('promise_failed', 'Провалено') }}
    </div>
    <div class="col-md-10">
        {{ Form::checkbox('promise_failed', 1, $promise->failed, ['class' => 'checkbox']) }}
    </div>
</div>

<div class="form-group">
    <div class="col-md-2">
        {{ Form::label('comments', 'Комментарии') }}
    </div>
    <div class="col-md-10">
        {{ Form::textarea('comments', null, ['class' => 'form-control', 'id' => 'quote_input']) }}
    </div>
</div>

<div id="create_tag_dlg" style="display: none">
    <div class="vue_app">
        <tag-editor></tag-editor>
    </div>
</div>

<div class="form-group">
    {{ Form::submit('Сохранить') }}
</div>

resources/views/backend/promises/index.blade.php
@extends('backend.layout')

@section('title', 'Обещания')

@section('content')
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <a href="{!! route('promise.create') !!}" class="btn btn-default">Создать</a>
            </div>
        </div>
        <table class="table">
            <thead>
            <tr>
                <td>id</td>
                <td>Политик</td>
                <td>Партия</td>
                <td>Организация</td>
                <td>Описание</td>
                <td colspan="2"></td>
            </tr>
            </thead>
            <tbody>
            @foreach ($promises as $promise)
                <tr>
                    <td>{!! $promise['id'] !!}</td>
                    <td>{!! implode(', ', $promise->politicians ? $promise->politicians->pluck('full_name')->toArray() : []) !!}</td>
                    <td>{!! implode(', ', $promise->parties ? $promise->parties->pluck('name')->toArray() : []) !!}</td>
                    <td>{!! implode(', ', $promise->organization ? $promise->organization->pluck('name')->toArray() : []) !!}</td>
                    <td>{!! $promise['description'] !!}</td>
                    <td>
                        {!! Form::model($promise, ['route' => ['promise.edit', $promise['id']], 'method' => 'get']) !!}
                        {!! Form::button('<span class="glyphicon glyphicon-edit"></span> Изменить', ['class' => 'btn btn-warning btn-sm', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                    <td>
                        {!! Form::model($promise, ['route' => ['promise.destroy', $promise['id']], 'method' => 'DELETE']) !!}
                        {!! Form::button('<span class="glyphicon glyphicon-remove"></span> Удалить', ['class' => 'btn btn-danger btn-sm', 'type' => 'submit']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>


    <div class="pagination">
        {!! $promises->links() !!}
    </div>
@endsection